"""Crystallization: emit system prompt, playbook, and runnable agent code."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .llm import LLMClient
from .models import ArtifactAnalysis, Playbook, SpecialistProfile
from .prompts import BUILD_PLAYBOOK, BUILD_SYSTEM_PROMPT


class Crystallizer:
    """
    Turns a SpecialistProfile + ArtifactAnalysis into three artifacts:
      1. A layered system prompt (Identity / Competencies / Heuristics / Guardrails / Failure Modes)
      2. A Playbook (steps, tools, guardrails)
      3. Runnable agent Python code with the system prompt baked in

    All file writes go through _atomic_write (write-to-tmp then rename) so a
    mid-write crash leaves the previous version intact.
    """

    def __init__(self, llm: LLMClient, playbook_dir: Path) -> None:
        self.llm = llm
        self.playbook_dir = playbook_dir

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def crystallize(
        self,
        profile: SpecialistProfile,
        analysis: ArtifactAnalysis,
    ) -> tuple[str, Playbook, str]:
        """Return (system_prompt, playbook, agent_code). Does not write to disk."""
        system_prompt = self._build_system_prompt(profile)
        playbook = self._build_playbook(profile, analysis)
        agent_code = self._build_agent_code(profile, system_prompt)
        return system_prompt, playbook, agent_code

    def rebuild_after_evolution(
        self,
        profile: SpecialistProfile,
    ) -> tuple[str, str]:
        """Re-emit system prompt and agent code after a profile update. No playbook LLM call."""
        system_prompt = self._build_system_prompt(profile)
        agent_code = self._build_agent_code(profile, system_prompt)
        return system_prompt, agent_code

    def save(self, playbook: Playbook, agent_code: str) -> tuple[Path, Path]:
        """Atomically write playbook JSON and agent code. Returns (playbook_path, agent_path)."""
        slug = playbook.domain.replace(" ", "_")
        playbook_path = self.playbook_dir / f"{slug}_v{playbook.version}.json"
        agent_path = self.playbook_dir / f"{slug}_agent.py"
        self._atomic_write(playbook_path, playbook.model_dump_json(indent=2))
        self._atomic_write(agent_path, agent_code)
        return playbook_path, agent_path

    # ------------------------------------------------------------------
    # Builders
    # ------------------------------------------------------------------

    def _build_system_prompt(self, profile: SpecialistProfile) -> str:
        return self._completion(
            system=BUILD_SYSTEM_PROMPT,
            user=f"SpecialistProfile:\n{json.dumps(profile.model_dump(), indent=2)}",
        )

    def _build_playbook(
        self,
        profile: SpecialistProfile,
        analysis: ArtifactAnalysis,
    ) -> Playbook:
        result = self._json_completion(
            system=BUILD_PLAYBOOK,
            user=(
                f"SpecialistProfile:\n{json.dumps(profile.model_dump(), indent=2)}\n\n"
                f"ArtifactAnalysis:\n{json.dumps(analysis.model_dump(), indent=2)}"
            ),
        )
        return Playbook(
            domain=profile.domain,
            steps=result.get("steps", []),
            tools=result.get("tools", []),
            guardrails=result.get("guardrails", []),
        )

    def _build_agent_code(self, profile: SpecialistProfile, system_prompt: str) -> str:
        """Template-based — deterministic, no LLM call."""
        sp_repr = repr(system_prompt)
        lines = [
            f'"""Crystallized specialist: {profile.domain}',
            f"Generated by Stem Agent. Convergence score: {profile.convergence_score:.2f}",
            '"""',
            "",
            "import os",
            "from anthropic import Anthropic",
            "",
            f"SYSTEM_PROMPT = {sp_repr}",
            "",
            "",
            "def run() -> None:",
            "    client = Anthropic()",
            '    model = os.getenv("STEM_MODEL", "claude-sonnet-4-6")',
            "    history: list[dict] = []",
            "",
            f'    print("Specialist active: {profile.domain}")',
            "    print(\"Type 'quit' to exit.\\n\")",
            "",
            "    while True:",
            '        user_input = input("You: ").strip()',
            '        if user_input.lower() in {"quit", "exit", "q"}:',
            "            break",
            "        if not user_input:",
            "            continue",
            "",
            '        history.append({"role": "user", "content": user_input})',
            "        response = client.messages.create(",
            "            model=model,",
            "            max_tokens=4096,",
            '            system=[{"type": "text", "text": SYSTEM_PROMPT, "cache_control": {"type": "ephemeral"}}],',
            "            messages=history,",
            "        )",
            "        reply = response.content[0].text",
            '        history.append({"role": "assistant", "content": reply})',
            '        print("\\nAssistant: " + reply + "\\n")',
            "",
            "",
            'if __name__ == "__main__":',
            "    run()",
        ]
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # I/O
    # ------------------------------------------------------------------

    def _atomic_write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.rename(path)

    # ------------------------------------------------------------------
    # LLM helpers
    # ------------------------------------------------------------------

    def _completion(self, system: str, user: str) -> str:
        return self.llm.complete(system=system, user=user, max_tokens=4096)

    def _json_completion(self, system: str, user: str) -> dict[str, Any]:
        text = self.llm.complete(system=system, user=user)
        if text.startswith("```"):
            text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        return json.loads(text)
